name: LightGBM ML CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Train model
        run: python src/train.py

      - name: Evaluate model
        run: python src/evaluate.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: models/model.pkl
